### ISSUE TITLE
In model unet_resnet, why do expand_dims for input_pred_softmax?

### ISSUE THREAD

**Issue by zwlshine** [JohnleeHIT/Brats2019#4]
In model unet_rest, you do expand_dims for input_pred_softmax, this change input_pred_softmax's shape from (1,96,96,96,2),if the input channel is 2, then to (1,96,96,96,1).
So, input_attention = forground_input_pred * input_img, input_attention get its shape(1,96,96,96,1), the input_attention's channel is 1,  but the input channel is 2, not equal. So, why do expand_dims? How it influence the segmentation result?

**Comment by JohnleeHIT** [comment]
Although i used the softmax function here, it actually a binary classification, aka. forground and background, input_pred_softmax[:, :, :, :, 1] takes the forground as the mask and do expand_dims to make sure the dimention is 4 and can multiply with the input image.   and if the input channal is 2, still works because of the broadcast mechanism of  Python.
